### ISSUE TITLE
Add a persian font

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-client#155]
Hi.

By setting the persian language in setting app, I want the whole desktop use a specefic persian font.

I put the fonts in a folder in src/client path and I add @font-face rules in src/client/index.scss. Am I correct? What else should I do?

**Comment by andersevenrud** [comment]
In order to be able to switch font based on context, the locale would have to be added to the `<html>` element. I thought this was already done, but I'll look at this now.

**Comment by andersevenrud** [comment]
The root element (body by default) now contains `data-locale` that you can use to determine what font to use. Add your font faces as normal, then ex:

```css
.osjs-root[data-locale="foo_BAR"] {
   font-face: your-font-face;
}
```

**Comment by mahsashadi** [comment]
where should I add this code?
I add the following code in `src/client/index.scss`, but it did not work.

```js

@font-face {
  font-family: Vazir;
  font-style: normal;
  font-weight: normal;
  src: url('./fonts/Vazir.eot');
  src: url('./fonts/Vazir.eot?#iefix') format('embedded-opentype'),
  url('./fonts/Vazir.woff2') format('woff2'),
  url('./fonts/Vazir.woff') format('woff'),
  url('./fonts/Vazir.ttf') format('truetype');
}
@font-face {
  font-family: Vazir;
  font-style: normal;
  font-weight: bold;
  src: url('./fonts/Vazir-Bold.eot');
  src: url('./fonts/Vazir-Bold.eot?#iefix') format('embedded-opentype'),
  url('./fonts/Vazir-Bold.woff2') format('woff2'),
  url('./fonts/Vazir-Bold.woff') format('woff'),
  url('./fonts/Vazir-Bold.ttf') format('truetype');
}
.osjs-root[data-locale="fa_FA"] {
  font-family: Vazir;
 }

```

**Comment by andersevenrud** [comment]
The index scss file is correct. What does devtools say about this?

**Comment by mahsashadi** [comment]
It has warnings: `Failed to decode downloaded font` and `OTS parsing error: invalid version tag`
The same fonts are working well inside a OSjs application.

Can it be about loader? I changed the `webpack.config` file as below:

```js
    {
        // test: /\.(svg|png|jpe?g|gif|webp)$/,
        test: /\.(svg|png|jpe?g|gif|webp|woff|woff2|eot|ttf)(\?.*$|$)/,
        use: [
          {
            loader: 'file-loader'
          }
        ]
      },

      {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        include: /typeface/,
        use: {
          loader: 'file-loader',
          options: {
            name: 'fonts/[name].[ext]'
          }
        }
      },
```

**Comment by andersevenrud** [comment]
The file-loaders just decides what path they end up with. Does not change the file in any way. Devtools actually tried loading it, right ? There wasn't like a 404 error or something ?

**Comment by mahsashadi** [comment]
> Devtools actually tried loading it, right ? 

Right

> ? There wasn't like a 404 error or something ?

No, just the mentioned warnings

**Comment by andersevenrud** [comment]
Maybe you could share this font so I can test mysefl ?

**Comment by mahsashadi** [comment]
Thanks, I have tested other fonts, the problem is not about that.

Sorry! the devtools shows that it does not try to load my font, some other names are shown in warnings:

![Screenshot from 2021-04-21 16-34-28](https://user-images.githubusercontent.com/70196035/115550959-aecc2600-a2bf-11eb-9bd5-5f6e72076c80.png)

**Comment by andersevenrud** [comment]
The only thing I can think of is that either the font is corrupt, or that they're not properly included. Do you see the files when you run webpack ?

Also, what's the contents of your Network tab in devtools ?

**Comment by mahsashadi** [comment]
> Do you see the files when you run webpack ?

Yes as below:

![Screenshot from 2021-04-24 16-21-49](https://user-images.githubusercontent.com/70196035/115957707-4082a000-a519-11eb-9886-f525ff86b957.png)


> some other names are shown in warnings:

Actually those warning will be disapeared when I comment `@import "~typeface-roboto/index.css";` line

> what's the contents of your Network tab in devtools ?

Nothing!

**Comment by andersevenrud** [comment]
Send me an archive with these fonts so I can try to reproduce this :)

**Comment by mahsashadi** [comment]
here is the folder I add in `src/client`
[fonts.zip](https://github.com/os-js/osjs-client/files/6370068/fonts.zip)

**Comment by andersevenrud** [comment]
Here's what I did:

1. Extracted fonts into `src/client/typeface` (you don't have to modify webpack config)
2. Added CSS typeface rules
3. Added `!important` to `font-family` rule


```css
@font-face {
  font-family: Vazir;
  font-style: normal;
  font-weight: normal;
  src: url('./typeface/Vazir.eot');
  src: url('./typeface/Vazir.eot?#iefix') format('embedded-opentype'),
  url('./typeface/Vazir.woff2') format('woff2'),
  url('./typeface/Vazir.woff') format('woff'),
  url('./typeface/Vazir.ttf') format('truetype');
}
@font-face {
  font-family: Vazir;
  font-style: normal;
  font-weight: bold;
  src: url('./typeface/Vazir-Bold.eot');
  src: url('./typeface/Vazir-Bold.eot?#iefix') format('embedded-opentype'),
  url('./typeface/Vazir-Bold.woff2') format('woff2'),
  url('./typeface/Vazir-Bold.woff') format('woff'),
  url('./typeface/Vazir-Bold.ttf') format('truetype');
}

.osjs-root[data-locale="fa_FA"] {
  font-family: Vazir !important;
 }
```

The reason it probably did not work for you is that the font-family is actually set in the javascript code via configuration. Because of this you have to add `!important` because of how CSS specificity works.
