### ISSUE TITLE
403 forbidden error while selecting mountpoint 

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-client#171]
**Sometimes** I can not access my files by selecting on all mountpoints, except Applications. It needs to refresh browser to work properly.
It shows forbidden 403 error.
I am using osjs in docker mode, build my own image.

![Screenshot from 2021-11-13 14-30-02](https://user-images.githubusercontent.com/70196035/141643822-9d89983c-d8cb-4ba9-be60-a70f71955b69.png)

**Dockerfile**: (I simplified this file here, there are some other packages installed)
```
FROM node:10
WORKDIR /usr/src/osjs
COPY . .
COPY hafez-entrypoint.sh .
RUN npm install
WORKDIR /usr/src/osjs

EXPOSE 8000

CMD ./hafez-entrypoint.sh
```
**Docker-compose**:
```
version: "3"
services:
  hafez:
    image: hafez/osjs:1.0
    restart: always
    container_name: hafez
    environment:
      - username=<USERNAME>
      - password=<PASSWORD>
    ports:
      - 8000:8000
```
