### ISSUE TITLE
bad location of search box in rtl languages 

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-client#200]
Search box is positioned badly when locale is set to Persian. 
![Screenshot from 2022-12-12 09-46-38](https://user-images.githubusercontent.com/70196035/206980374-9b26ae9a-7fb8-4ba4-bb66-5597ef673ac7.png)

**Comment by mahsashadi** [comment]
I have fixed this issue by adding this style:

```css
.osjs-root[data-locale='fa_FA'] {
  
  .osjs-search{
    direction: ltr;
  }

  .osjs-search *{
    direction: rtl;
  }
 }
```

How can I fix that in your repo?
